// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFoBs5gr0QZMaIFbfKZmGIod_w_wEqm8',
    appId: '1:260244666959:web:c6e9730b06abfd1aabc83a',
    messagingSenderId: '260244666959',
    projectId: 'harmonia-playground',
    authDomain: 'harmonia-playground.firebaseapp.com',
    databaseURL: 'https://harmonia-playground-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harmonia-playground.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCOQOVldsXL2MaIbzndRaoIehprNzqFw',
    appId: '1:260244666959:android:6d7f4e40362ed5e9abc83a',
    messagingSenderId: '260244666959',
    projectId: 'harmonia-playground',
    databaseURL: 'https://harmonia-playground-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harmonia-playground.firebasestorage.app',
  );
}
